### ISSUE TITLE
[Sacerdote] Alarido psíquico ID: 8122

### ISSUE THREAD

**Issue by paellaencol** [RoDNet/Bugtracker-Infinium-4.3.4#1493]
La spell del sacerdote: Alarido psíquico, debería provocar que los enemigos en un radio de 8metros huyeran aterrorizados durante 8segundos (esto sucede).

Sin embargo debería ocurrir lo mismo que sucede con otros efectos de miedo de otras clases, como  por ejemplo el "miedo" (5782), o el "aullido de terror" (5484) del brujo, este debuff de "Miedo" no debería irse hasta ya pasado unos cuantos golpes (he aquí el problema).

En la actualidad y tal como está funcionando tiene un uso muy escaso, ya que a la mínima de daño (ya salta solo con 1 punto de daño), este efecto de miedo se desvanece

Primero lanzo alarido a 4 objetivos:
http://imageshack.us/a/img109/6732/l1ud.jpg

<a href="http://imageshack.us/photo/my-images/109/l1ud.jpg/" target="_blank"><img src="http://imageshack.us/a/img109/6732/l1ud.th.jpg" border="0"/></a>

Luego uso una spell de daño de área, que infinge en torno a 1500 puntos de daño, y como se puede ver el debuff alarido psiquico se ha desvanecido de todos los objetivos, cuando debería de haberlo hecho después de haber recibido unos cuantos golpes más:

http://imageshack.us/a/img546/3207/3xq9.jpg

<a href="http://imageshack.us/photo/my-images/546/3xq9.jpg/" target="_blank"><img src="http://imageshack.us/a/img546/3207/3xq9.th.jpg" border="0"/></a>

P.S. Huelga decir que alarido psíquico comparte diminishing returns con otros efectos de controles de masas, englobados en la categoría de "Miedo", similares

**Comment by crowel** [comment]
Adjunto el siguiente enlace, para probar tu teoría ya que se necesitan pruebas^^
http://wowpedia.org/Psychic_Scream

Y quiero mencionar está parte:
"Psychic Scream can allow priests time to cast spells uninterrupted, whether to heal or to deal damage, although direct damage spells (and [Mana Burn]) will usually cause the effect to break. It is particularly useful when attempting to use Mind Control on the target, due to its lengthy cast time. When attempting to Mind Control the target off a cliff or edge, Psychic Scream can be doubly useful in propelling them most or all of the way toward it, although it will not in itself cause targets to walk off high edges."
- Como dice ahi, alarido psiquico puede dar tiempo a los sacerdotes a lanzar hechizos ininterrumpidamente , ya sea para curar o hacer daño, aunque los efectos de daño directo y/o quemadura de mana, "por lo general" causa que rompa el efecto"

*Actualmente como comenta Jesu el efecto se rompe directamente al primer toque sea muy elevado el daño o muy bajo.

Luego tambien quiero mencionar esta otra:
"While direct damage will almost always break the effect, by placing several DoTs upon a target before fearing them and using Mind Flay, Shadow priests can cause significant amounts of damage while the enemy is helpless to respond, or escape."

Mientras el daño directo rompe casi siempre el efecto, mediante la colocacion de varis dots(pegatinas) antes de usar el alarido y el uso tortura mental, los sacerdotes de las sombras pueden causar grandes cantidades de daño mientras que el enemigo es incapaz de responder, o escapar.
- Como dice en este segundo párrafo, cuando se colocan varios dots(pegatinas) antes de usar el alarido y el uso de tortura mental, el alarido no debe desaparecer hasta recibir una gran cantidad de daño de los dots que tenia puesto. Actualmente eso no ocurre tampoco ya que si el enemigo tenia un dot puesto, al recibir el minimo daño del mismo el alarido deja de hacer efecto.

Ambas dinamicas del alarido no funcionan que en resumen despues de todo este testamento es lo siguiente.
1º- Al usar alarido debe de estar la posibilidad de desaparecer al recibir una lígera cantidad de daño, actualmente desaparece siempre a la prímera.
2º- Cuando un jugador tiene puesto los dots del sacerdote sombras y utilizas alarido psiquico no debe de desaparecer hasta recibir una gan cantidad de daño cosa que tampoco esta funcionando ya que al primer golpe se libera del alarido.

Espero que mi comentario y informacion sirva para la reparación del mismo.

Un saludo.

**Comment by paellaencol** [comment]
Cierro, ya esta fixeado, no crowel?

**Comment by crowel** [comment]
Sip aunque veo que no se comento ya lo arreglaron, no desaparece hasta recibir una cantidad moderada de daño tras usarlo entre 5-10k

Y si se usa teniendo dots el objetivo no se liberara a no ser de recibir una alta cantidad de daño de esos dots o un golpe fuerte a mayores.
Esta tan bien reparado que hasta con el mana burn se quita al primer toque como debe ser.
Gracias por la reparación, un saludo.

**Comment by paellaencol** [comment]
Creo que ya vuelve a ir bien
