### ISSUE TITLE
[Misión] Península de fuego infernal: Fortificaciones del Fuego Infernal

### ISSUE THREAD

**Issue by Pegasu5** [RoDNet/Bugtracker-Infinium-4.3.4#3351]
Misión:  
http://es.wowhead.com/quest=13409 Horda 
http://es.wowhead.com/quest=13410 Alianza

Problema es que al estar ya capturada la base por ejm si soy horda y voy a ella ni por que me ponga a hacer hijos con una sexy elfa que encontré por ahí me la cuenta, tiene que venir un alianza a tomar la bases para yo tomarla de nuevo.supongo que lo mismo para el otro lado.

Gracias

**Comment by Compresor** [comment]
Pero eso no es bug no? Porque dice capturar, y si ya esta capturado tienes qe esperarte. Es como tol barad, si tu quieres utilizar los vehiculos tienes qe esperar a atacar y hasta que la faccion contraria controle tol'barad no podrás, pues esto es igual diría yo. En mi opinión diría que no está bug.

**Comment by Compresor** [comment]
Mira lo que pone aqui: http://es.wowhead.com/quest=13409#english-comments
Simple quest. Just run inside of each of the three forts and stand there until it says that you've captured it. The amount of time that this take varies. Two things to note are:

1) You can only capture them if they are neutral or are controlled by the other faction. If they are controlled by the other faction, they will first turn neutral after you standing there for a while. Keep standing there and you will soon capture it.

2) If you are on a PvE server, you will have to be flagged for PvP in order to capture any of the forts.

Good luck.

Lo mismo que te he dicho.
