### ISSUE TITLE
[Item Mazmorra] Fin de los Dias 

### ISSUE THREAD

**Issue by Savian123** [RoDNet/Bugtracker-Infinium-4.3.4#3853]
Buenas solo quiero comentar que la mazmorra fin de los dias en el boss final el item Reloj de Arena no resucita a los miembros del grupo caido aunque deberia hacerlo aparte de lo que ya hace de recuperar cds y recuperar todo el mana y la vida  gracias :D como dice en esta descripcion del efecto 

The Reverse Time effect rewinds everything back to the beginning of the encounter. The reversal restores each player's health and mana, then resets all of their ability cooldowns. The reversal also removes all Distortion Bombs

te devuelve todo al principio del encuentro pero como Murozond es inmune a los efectos del reloj el no se cura pero si a todos los miembros del grupo y vuelven a la vida ya que al inicio del combate estais todos vivos no solo los cds , el hp y el mana

**Comment by Kiritoo** [comment]
Arreglado, falta compilar.

**Comment by Kiritoo** [comment]
Tengo que preguntarlo antes de compilar, ya que ahora he revisado unos cuantos videos y notas del oficial y no consigo ver en ninguno esto de que se reviva a los jugadores, lo de la salud y mana, más las habilidades lo dice claramente, pero lo de revivir a los jugadores no.
Si haces el favor de añadir un comentario del oficial o un video que lo demuestre te lo agradezco, cuando revisemos que realmente es asi lo compilaremos.
Gracias.

**Comment by Kiritoo** [comment]
The player assigned to activate the hourglass should wait until one of the following conditions occurs:

   The tank or healer dies
   The number of Distortion areas makes it hard for DPS to stay in range of Murozond.
   The hourglass activator is at imminent risk of death, with no player available as backup to activate the hourglass

Fallen players should not release when dying before all hourglasses are consumed, since the hourglass will return the player to their living state. Battle resurrections reset their cooldowns as well, but rarely have much utility in this fight.

http://wowpedia.org/Murozond

Todo OK!.

**Comment by lomero** [comment]
al parecer el reloj si revive a la gente segun wowpedia
