### ISSUE TITLE
Rogue Esfumarse

### ISSUE THREAD

**Issue by Pitenser** [RoDNet/Bugtracker-Infinium-4.3.4#4530]
Esfumarse: http://es.wowhead.com/spell=1856#modified-by
La habilidad tiene bastantes fallos; 
1- Cuando te lanzan un hechizo y tu lo usas te entra igual en lugar de esquivarlo.
2- No elimina los efectos de reducción de movimiento, si lo usas te quedas en el mismo lugar lo que en sigilo. 
3- No elimina la marca de cazador.

**Comment by Sagittariu5** [comment]
From a Blue Post:
The purpose of Vanish in Cataclysm is to get back into stealth. If you want to avoid harmful effects, use Cloak of Shadows.

We grew tired, as did many players, of "Vanish never works LOL" so we looped back to the original intent of Vanish being about stealth. That is why the tooltip specifically says that harmful effects won't break Vanish, but does _not_ say that the harmful effects won't land. We understand some rogues liked using Vanish to "dodge spells" but the ability was never designed to work that way and never was going to work that way very well. The more we tried to let it be a damage negater, the harder time we had letting it guarantee stealth.

There is a current live bug with pets and guardians being able to still target a vanished rouge. That will be fixed in an upcoming patch. Other than that, we are not aware of any issues that keep the ability from working as advertised. Most concerns seems to be rogues who want it to work a different way.

Font: http://es.wowhead.com/spell=1856#english-comments

PD: Aun asi de los cazadores no te vas a escapar. xd

**Comment by Pitenser** [comment]
Eso es un comentario de una persona, el vanish en cataclyms funciona exactamente igual que en los parches anteriores salvo que no te pueden sacar los 3 segundos siguientes después de habértelo tirado y con glifo creo que puede llegar a 5. Es decir, elimina efectos de reducción de movimiento, esquiva hechizos y elimina marca del cazador, es mas en el server estaba funcionando bien menos el esquivar hechizos.

PD: No intento escaparme de nadie, solo poder corregir errores que tiene el personaje.
Un saludo

**Comment by Overseer101** [comment]
Pitenser, le tengo que dar la razon a saggitarius, el esfumarse no evita que te entren spells, evita que te saquen de sigilo los dots por ejemplo durante x segundos pero los hechizos lanzados antes de eso te entraran igual, para eso esta la capa de las sombras, que es la que quita tambien marca del cazador aparte de evitar que te entren los hechizos.

Lo de que libra de todos los efectos de reduccion de movimiento si tienes razon.

**Comment by efectokoleos** [comment]
arreglado, no quita marca del cazador
